client_id: 
  development: ca_1PeWkKK3FZct85SCAQDJlcBhwxLqBhMF
  test: ca_1PeWkKK3FZct85SCAQDJlcBhwxLqBhMF
  production: ca_1PeWj5uoJqbfcMx0Sv4KQz81eVgjukTk
api_key:
  kiindly:
    secret:
      test: 3vAWJJUrN1pyhnUOLvVCNehhrAEJ5gkS
      live: wb0cLIk2REiQaBg5FvLA8ltD1Hrk3vLY
    publishable:
      test: pk_3hEW6oAUjy89JDRHdYgeRwnSRfguG
      live: pk_va9FTtsmhIlv0cUIdcnaXsCMfIhr9
  lts:
    stripe_user_id: acct_1zIGqUbwXH8i6kdEkLB6
    refresh: rt_1zIQP7kRDzEr6pxfEGbjU3QQ3AZ94nRmGnFJ5cAWSXrKi517
    secret:
      test: sk_test_eFKbXgo9FIgi2icDBHryZkA0
      live: sk_live_BrefMrBLxMUlOq0OVNbcqcHp
    publishable:
      test: pk_test_nF6pGtowUM7oGXQKUNG2AA0f
      live: pk_live_T6y5ApiKEtF9bAZiaZ9bAuQg
    mode: live
